version: '3.9'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='bdproyecto'
      - MYSQL_USER='sgonzalez6'
      - MYSQL_PASSWORD='CQCcqc19'
      - MYSQL_HOST='104.154.102.101'
      - MYSQL_ROOT_PASSWORD='CQCcqc19'
    volumes:
      - /tmp/code/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - /tmp/code/mysqld:/run/mysqld
    depends_on:
      - db